unleashed:
  api_id: ""
  api_key: ""

search:
  warehouse_code: "W6"
  customer_name: "Tesco"
  depot_name: "Belfast"
  product_codes:
    - "BOSH0077"
    - "BOSH0079"
    - "BOSH0080"
    - "BOSH0101"
    - "BOSH0102"
    - "BOSH0103"
    - "BOSH0104"

email:
  sender: ""
  app_password: ""
  recipients:
    - "Max.Jordan@turners-distribution.com"
    - "tesco.irishdocs@turners-distribution.com"
    - "Ben.Reader@turners-distribution.com"
    - "Julie.Mallows@turners-distribution.com"
    - "Nick.Granger@turners-distribution.com"
  body: "Please find attached the PO report for delivery on {date}."
